"""baseline schema

Revision ID: 4ce213945fbd
Revises:
Create Date: 2026-06-20 10:06:08.402472
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "4ce213945fbd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agentindex",
        sa.Column("qualified_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_alias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_md_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("indexed_at_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tools", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("qualified_name"),
    )
    with op.batch_alter_table("agentindex", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agentindex_agent_name"), ["agent_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_agentindex_repo_alias"), ["repo_alias"], unique=False)

    op.create_table(
        "globalsetting",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "layoutprofile",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("toml_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "mcpservercache",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("definition_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "registeredrepo",
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("last_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("alias"),
    )
    op.create_table(
        "ruleindex",
        sa.Column("qualified_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_alias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rule_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rule_md_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("indexed_at_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("qualified_name"),
    )
    with op.batch_alter_table("ruleindex", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ruleindex_repo_alias"), ["repo_alias"], unique=False)
        batch_op.create_index(batch_op.f("ix_ruleindex_rule_name"), ["rule_name"], unique=False)

    op.create_table(
        "skillindex",
        sa.Column("qualified_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_alias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill_md_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("indexed_at_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prereqs", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provides", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("qualified_name"),
    )
    with op.batch_alter_table("skillindex", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skillindex_repo_alias"), ["repo_alias"], unique=False)
        batch_op.create_index(batch_op.f("ix_skillindex_skill_name"), ["skill_name"], unique=False)

    op.create_table(
        "template",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template")
    with op.batch_alter_table("skillindex", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skillindex_skill_name"))
        batch_op.drop_index(batch_op.f("ix_skillindex_repo_alias"))

    op.drop_table("skillindex")
    with op.batch_alter_table("ruleindex", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ruleindex_rule_name"))
        batch_op.drop_index(batch_op.f("ix_ruleindex_repo_alias"))

    op.drop_table("ruleindex")
    op.drop_table("registeredrepo")
    op.drop_table("mcpservercache")
    op.drop_table("layoutprofile")
    op.drop_table("globalsetting")
    with op.batch_alter_table("agentindex", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agentindex_repo_alias"))
        batch_op.drop_index(batch_op.f("ix_agentindex_agent_name"))

    op.drop_table("agentindex")
    # ### end Alembic commands ###
