"""archetype index

Revision ID: d7424c089c0e
Revises: 4ce213945fbd
Create Date: 2026-06-20 10:22:42.696125
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "d7424c089c0e"
down_revision: str | None = "4ce213945fbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archetypeindex",
        sa.Column("qualified_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_alias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("archetype_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instruction_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("available", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("indexed_at_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("qualified_name"),
    )
    with op.batch_alter_table("archetypeindex", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_archetypeindex_archetype_name"), ["archetype_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_archetypeindex_repo_alias"), ["repo_alias"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("archetypeindex", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_archetypeindex_repo_alias"))
        batch_op.drop_index(batch_op.f("ix_archetypeindex_archetype_name"))

    op.drop_table("archetypeindex")
    # ### end Alembic commands ###
