"""Capture TUI screenshots for README/gif demos."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from aim.core import repos
from aim.tui.app import AimApp


def _run_git(args: list[str], cwd: Path) -> None:
    subprocess.run(args, cwd=cwd, check=True, capture_output=True)


def _make_source_repo(root: Path, files: dict[str, str]) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    _run_git(["git", "init", "-q", "-b", "main"], root)
    _run_git(["git", "config", "user.email", "test@example.com"], root)
    _run_git(["git", "config", "user.name", "Test"], root)
    _run_git(["git", "config", "commit.gpgsign", "false"], root)
    for rel, content in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    _run_git(["git", "add", "."], root)
    _run_git(["git", "commit", "-q", "-m", "initial"], root)
    return root


def _make_bare_remote(working_repo: Path, dest: Path) -> Path:
    subprocess.run(
        ["git", "clone", "--bare", "--quiet", str(working_repo), str(dest)],
        check=True,
        capture_output=True,
    )
    return dest


def _setup_repo_with_skills(tmp_path: Path, files: dict[str, str]) -> None:
    working = _make_source_repo(tmp_path / "src", files)
    bare = _make_bare_remote(working, tmp_path / "bare.git")
    repos.add("anthropic", f"file://{bare}")


def _svg_to_png(svg_path: Path, png_path: Path, *, width: int | None = None) -> None:
    """Rasterize a Rich/Textual SVG to PNG.

    On macOS we use ``sips`` because it resolves the embedded web fonts
    correctly. On other platforms we fall back to any available
    ``rsvg-convert`` / ``cairosvg`` command, but the README assets are
    generated by the maintainer on macOS so this is the happy path.
    """
    if sys.platform == "darwin" and shutil.which("sips"):
        cmd = ["sips", "-s", "format", "png", str(svg_path), "--out", str(png_path)]
        if width:
            cmd.extend(["-Z", str(width)])
        subprocess.run(cmd, check=True, capture_output=True)
        return

    if shutil.which("rsvg-convert"):
        cmd = ["rsvg-convert", "-o", str(png_path), str(svg_path)]
        if width:
            cmd.extend(["-w", str(width)])
        subprocess.run(cmd, check=True, capture_output=True)
        return

    raise RuntimeError(
        "No SVG rasterizer found. README assets are generated with macOS "
        "`sips`; on Linux install `rsvg-convert` (librsvg)."
    )


def _make_gif(png_paths: list[Path], gif_path: Path, *, delay_ms: int = 1500) -> None:
    """Stitch PNG frames into a looping GIF using ImageMagick."""
    if not shutil.which("convert") and not shutil.which("magick"):
        raise RuntimeError("ImageMagick 'convert'/'magick' not found; cannot build GIF")
    binary = "magick" if shutil.which("magick") else "convert"
    delay_centis = max(delay_ms // 10, 1)
    cmd = [
        binary,
        "-delay",
        str(delay_centis),
        "-loop",
        "0",
        *[str(p) for p in png_paths],
        str(gif_path),
    ]
    subprocess.run(cmd, check=True, capture_output=True)


async def capture_screenshots(output_dir: Path) -> list[Path]:
    import aim.core.db as db
    import aim.core.paths as paths

    home = Path(tempfile.mkdtemp(prefix="aim-capture-"))
    original_cwd = Path.cwd()
    os.chdir(home)
    # Sandbox global state so we don't conflict with a real user database.
    os.environ[paths._PROJECT_DIR_ENV] = str(home)
    paths.ensure_global_dirs()
    db._engine = db.get_engine(paths.db_path())
    try:
        # Pre-seed global state for populated screens. Use short fixture paths
        # so the captured repo URL is as tidy as possible.
        _setup_repo_with_skills(
            home / "f",
            {
                "skills/review/SKILL.md": "# Review\n\nReview a PR.\n",
                "skills/format/SKILL.md": "# Format\n\nApply formatting.\n",
                "rules/be-concise.md": "---\ndescription: brevity\n---\nBe concise.\n",
            },
        )

        app = AimApp()
        screenshots: list[Path] = []

        async with app.run_test() as pilot:
            await pilot.pause()

            scenes = [
                ("main", []),
                ("repos", ["r"]),
                ("skills", ["s"]),
                ("rules", ["u"]),
                ("project", ["p"]),
                ("config", ["c"]),
            ]

            for name, keys in scenes:
                # Return to the main menu before opening the next screen.
                if type(app.screen).__name__ != "MainScreen":
                    await pilot.press("b")
                    for _ in range(3):
                        await pilot.pause()
                for key in keys:
                    await pilot.press(key)
                    await pilot.pause()
                # Give the new screen time to mount and render.
                for _ in range(5):
                    await pilot.pause()
                filename = app.save_screenshot(filename=f"{name}.svg", path=str(output_dir))
                screenshots.append(Path(filename))

        return screenshots
    finally:
        shutil.rmtree(home, ignore_errors=True)
        os.chdir(original_cwd)


def main(argv: list[str]) -> None:
    output_dir = Path(argv[1]) if len(argv) > 1 else Path.cwd() / "screenshots"
    output_dir.mkdir(parents=True, exist_ok=True)

    svg_paths = asyncio.run(capture_screenshots(output_dir))

    png_paths: list[Path] = []
    for svg in svg_paths:
        png = svg.with_suffix(".png")
        _svg_to_png(svg, png, width=640)
        png_paths.append(png)
        print(f"  {png}")

    gif_path = output_dir / "demo.gif"
    _make_gif(png_paths, gif_path, delay_ms=1500)
    print(f"  {gif_path}")


if __name__ == "__main__":
    import asyncio

    main(sys.argv)
